// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type FilterInput struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Mutation struct {
}

type Product struct {
	ID          string             `json:"id"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Price       float64            `json:"price"`
	Stock       int32              `json:"stock"`
	Category    string             `json:"category"`
	Attributes  *ProductAttributes `json:"attributes"`
	Images      []string           `json:"images"`
	Ratings     float64            `json:"ratings"`
	CreatedAt   string             `json:"createdAt"`
}

type ProductAttributes struct {
	Color string `json:"color"`
	Size  string `json:"size"`
}

type ProductAttributesInput struct {
	Color string `json:"color"`
	Size  string `json:"size"`
}

type ProductInput struct {
	Title       string                  `json:"title"`
	Description string                  `json:"description"`
	Price       float64                 `json:"price"`
	Stock       int32                   `json:"stock"`
	Category    string                  `json:"category"`
	Attributes  *ProductAttributesInput `json:"attributes"`
	Images      []string                `json:"images"`
	Ratings     float64                 `json:"ratings"`
}

type Query struct {
}

type User struct {
	ID       *string `json:"id,omitempty"`
	Name     *string `json:"name,omitempty"`
	Email    *string `json:"email,omitempty"`
	Password *string `json:"password,omitempty"`
	Role     *string `json:"role,omitempty"`
}
